name: 'Terraform-CI'

on:
  pull_request:

permissions:
  id-token: write
  contents: read

concurrency:
  group: aws-control
  cancel-in-progress: false

jobs:
  terraform:
    name: 'Terraform Test'
    runs-on: ["self-hosted", "Linux", "noble"]
    timeout-minutes: 240
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      ROLE_ARN: "arn:aws:iam::303467602807:role/kibana-tester"
      CI_TEST_TOKEN: ${{ secrets.CI_TEST_TOKEN }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: "${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.workflow }}-${{ github.run_id }}"
          aws-region: "us-west-1"
          role-duration-seconds: 28800

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Setup Python Environment
        run: make bootstrap

      - name: Code Style Check
        run: make lint

      - name: Terraform Tests
        run: make test
